<a href="https://colab.research.google.com/github/NikhilGurrapu/PCA_step_by_step/blob/main/PCA_step_by_step.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing libraries

In [14]:
import numpy as np
import pandas as pd

# creating dataframe

In [15]:
mu_vec1 = np.array([0,0,0])
print("mu_vec1: ",mu_vec1)
cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
print("cov_mat1: ",cov_mat1)
class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20)
print("class1_sample: \n",class1_sample)

df = pd.DataFrame(class1_sample,columns=['feature1','feature2','feature3'])
df['target'] = 1

mu_vec1:  [0 0 0]
cov_mat1:  [[1 0 0]
 [0 1 0]
 [0 0 1]]
class1_sample: 
 [[-0.19119006  0.67135719 -0.88911429]
 [-0.5531838   0.41928646  0.09352204]
 [ 1.38768704  1.21951138 -0.14732446]
 [-0.54797365  0.97343793 -0.35254364]
 [ 0.55983921 -0.68799303 -0.56791308]
 [ 2.18482742  0.11371779 -0.36083313]
 [ 0.3678131  -0.52715395 -0.59912086]
 [-0.01788594  0.4841922  -0.91435291]
 [-0.79252151  0.38851451  1.37916044]
 [-0.37299649 -0.10590393  1.17813759]
 [ 0.80724952  2.06712942  1.79758381]
 [ 0.01109558 -0.72065175  0.52564497]
 [ 0.59957875  0.6313926  -0.39803961]
 [-1.09722813  0.1314242   0.29026828]
 [ 1.64505968 -0.29323891 -0.40889798]
 [ 0.35593002 -0.51215993  1.98072407]
 [-0.00786806 -0.24648098  1.60258141]
 [-0.23993993 -0.4595059  -0.49973505]
 [ 0.50048487 -0.3636805   0.53548107]
 [-1.03466916 -2.01553242 -0.16217517]]


In [16]:
df.shape

(20, 4)

In [17]:
mu_vec2 = np.array([1,1,1])
cov_mat2 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, 20)

df1 = pd.DataFrame(class2_sample,columns=['feature1','feature2','feature3'])

df1['target'] = 0

df = df.append(df1,ignore_index=True)

df = df.sample(40)
     

df.head()

feature1  feature2  feature3  target
35  0.218051  1.715630  1.765456       0
3  -0.547974  0.973438 -0.352544       1
1  -0.553184  0.419286  0.093522       1
8  -0.792522  0.388515  1.379160       1
12  0.599579  0.631393 -0.398040       1

In [18]:
import plotly.express as px
#y_train_trf = y_train.astype(str)
fig = px.scatter_3d(df, x=df['feature1'], y=df['feature2'], z=df['feature3'],
              color=df['target'].astype('str'))
fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))

fig.show()

# Step 1 - Apply standard scaling

In [19]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

df.iloc[:,0:3] = scaler.fit_transform(df.iloc[:,0:3])

# Step 2 - Find Covariance Matrix

In [20]:
covariance_matrix = np.cov([df.iloc[:,0],df.iloc[:,1],df.iloc[:,2]])
print('Covariance Matrix:\n', covariance_matrix)

Covariance Matrix:
 [[1.02564103 0.35171653 0.21484164]
 [0.35171653 1.02564103 0.41542184]
 [0.21484164 0.41542184 1.02564103]]


# Step 3 - Finding EV and EVs

In [21]:
eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)

In [22]:
eigen_values

array([1.68697874, 0.81501827, 0.57492606])

In [23]:
eigen_vectors

array([[-0.52256651, -0.78258083,  0.3383659 ],
       [-0.63517625,  0.09259619, -0.76679663],
       [-0.56874895,  0.61562422,  0.54546443]])

In [24]:
pc = eigen_vectors[0:2]
pc

array([[-0.52256651, -0.78258083,  0.3383659 ],
       [-0.63517625,  0.09259619, -0.76679663]])

In [25]:
transformed_df = np.dot(df.iloc[:,0:3],pc.T)
# 40,3 - 3,2
new_df = pd.DataFrame(transformed_df,columns=['PC1','PC2'])
new_df['target'] = df['target'].values
new_df.head()

PC1       PC2  target
0 -0.188815 -0.371607       0
1  0.060744  1.591594       1
2  0.635115  1.212633       1
3  1.197729  0.396092       1
4 -0.253039  0.911913       1

In [26]:
new_df['target'] = new_df['target'].astype('str')
fig = px.scatter(x=new_df['PC1'],
                 y=new_df['PC2'],
                 color=new_df['target'],
                 color_discrete_sequence=px.colors.qualitative.G10
                )

fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))
fig.show()